# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ricardo Lara | Developer
email: alejandro.elara@live.com
# description: > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
description: Want more people to see your awsome servise/pictures/ideas? I can help you to do just that! Having a web page, helps your buisness to grow exponesialy, and also is more professional.<br>Just get in touch with me.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alejandrlara12.github.io/" # the base hostname & protocol for your site
twitter_username: AlejandrLara12
github_username:  AlejandrLara12

# Build settings
markdown: kramdown
